language: android

sudo: false

install: true

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25

script: 
  - jdk_switcher use oraclejdk8
  - ./gradlew relinker:testReleaseUnitTest
